### ISSUE TITLE
Demo Failed to instantiate module 

### ISSUE THREAD

**Issue by DannyGokey** [zachsoft/Ionic-Material#90]
Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:modulerr] Failed to instantiate module ionic-material due to:
Error: [$injector:nomod] Module 'ionic-material' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

how can i fix it?

**Comment by niwasmala** [comment]
I also had same experience, please see issue #11.
The demo using older version of ionic-material, use bower to update. And also, change the index.html file
from
```
<link href="lib/ionic-material/ionic.material.min.css" rel="stylesheet">
<script src="lib/ionic-material/ionic.material.min.js"></script>
```
to
```
<link href="lib/ionic-material/dist/ionic.material.min.css" rel="stylesheet">
<script src="lib/ionic-material/dist/ionic.material.min.js"></script>
```
Hope this help.

**Comment by DannyGokey** [comment]
doesn't work for me.
i fix this by copy bower-component/ionic-material   to www/lib  and replace it.. then it worked...

maybe these files are not the same version.

**Comment by geoffreyporto** [comment]
Hi, These steps work for me.

Step 1:

Copy folder <root>/ionic-material/dist to <root>/ionic-material/demo/www/lib/ionic-material

Step 2:
   Change the index.html file
from

<link href="lib/ionic-material/ionic.material.min.css" rel="stylesheet">
<script src="lib/ionic-material/ionic.material.min.js"></script>
to

<link href="lib/ionic-material/dist/ionic.material.min.css" rel="stylesheet">
<script src="lib/ionic-material/dist/ionic.material.min.js"></script>

Done!

Hope this help.

**Comment by zigzag-way** [comment]
Change the /ionic-material/demo/www/index.html file
from
to

What do you mean?

**Comment by c0rn0** [comment]
Is this the true solution though?  I've also updated the necessary files with what was installed with bower, but still no luck?

I've read here as well:
https://docs.angularjs.org/error/$injector/unpr?p0=ionicMaterialInkProvider%20%3C-NaNonicMaterialInk%20%3C-%20LoginCtrl

Is one perhaps also suppose to make JS changes?

**Comment by 0v3rst33r** [comment]
Is this the true solution though?  I've used the files created by the bower install and I still get the same error.  I did go read at:

https://docs.angularjs.org/error/$injector/unpr?p0=ionicMaterialInkProvider%20%3C-NaNonicMaterialInk%20%3C-%20LoginCtrl

Is one perhaps suppose to make some JS change as well?
